on:
  pull_request:
    paths:
      - "app/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  format-app:
    uses: ./.github/workflows/reusable-node-pnpm-format.yml
    with:
      working_directory: ./app
