on:
  pull_request:
    paths:
      - "app-bff/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  format-app-bff:
    uses: ./.github/workflows/_reusable-node-pnpm-format.yml
    with:
      working_directory: ./app-bff
